### ISSUE TITLE
Treatment period in graphs

### ISSUE THREAD

**Issue by ErikaBraith** [bquistorff/synth_runner#10]
Hi, I'm using synth_runner (version 1.4.0) on Stata/MP 13.1 for Mac (64-bit Intel). When I use the trends option, the treatment line gets shifted to the year prior than I specified. Is that to be expected?

**Comment by bquistorff** [comment]
I don't seem to have this issue. When I run the below with and without the `trends` option, the graphs have the exact same treatment 
```
synth_runner cigsale beer(1984(1)1988) lnincome(1972(1)1988) retprice age15to24 cigsale(1987) cigsale(1980) cigsale(1975), trunit(3) trperiod(1989) gen_vars
```
Possibly this was inadvertently fixed in newer releases, so I'd try that. Also note that you can use the `trlinediff` option to the graphing commands to set the horizontal offset of the line manually.
