### ISSUE TITLE
Error 430

### ISSUE THREAD

**Issue by GAlbuquerque** [bquistorff/synth_runner#5]
First of all I would like to thank you for providing the synth_runner package and being open to discuss its bugs. My problem is that when I run synth_runner I get the following error message:

Estimating the treatment effects
could not calculate numerical derivatives
flat or discontinuous region encountered
r(430);

My understanding is that one of the multiple synthetic controls could not be calculated and this made the whole program to stop. As I have many placebos units in my dataset, I think it would be better to just ignore these problematic units. Is there a way for doing this?

I use Stata13 and synth_runner version 1.1.5.

Thank you again.

**Comment by bquistorff** [comment]
The program ignores errors in estimation for the placebos, but not for treated units (your error is with treated). Not ignoring errors with the treated units was intentional so that users would know explicitly what treatment effect they are estimating (over which treated units). You should drop the treated units that cause problems before running `synth_runner`. I've just updated the program to display a more informative error message saying which treated unit was the problem. See if this helps.

**Comment by GAlbuquerque** [comment]
Thank you for your quick response. I will try to discover which trated unit
is the problematic one.

2016-07-10 22:33 GMT-03:00 Brian Quistorff <notifications@github.com>:
